cashflow/urls.py
from django.urls import path, include, re_path
from cashflow import views as CashView

urlpatterns = [
    path('opbal/<int:id>/', CashView.customer_details, name='opening_details'),
    path('opbal/<int:id>/term/<int:term>/',CashView.monthly_details, name="customer_month_details"),
    path('opbal/term/<int:term>', CashView.term_monthly_details, name="term_monthly"),
] 

app_name = "cashflow"

fEN/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings


from rest_framework import routers

router = routers.DefaultRouter()

from accounts import api
from notifications import urls as notifications_urls

urlpatterns = [
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('app/', admin.site.urls),
    path('users/', include('users.urls')),
    path('others/', include(router.urls)),
    path('data', api.generalModelViewSet.as_view()),
    re_path('^inbox/notifications/', include(notifications_urls, namespace='notifications')),
    path('appuser/notifications', include('market.urls')),
    path('appuser/cash', include('invoice.urls')),
    path('appuser/cashflow', include('cashflow.urls')),
] 

router.register(r'images', api.ImageViewSet)

urlpatterns += router.urls

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # from django.conf.urls import url
    # # Serve static and media files from development server
    # from django.views.static import serve
    # urlpatterns = [
    # url(r'^media/(?P<path>.*)$', serve, {'document_root': 
    #     settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': 
    #     settings.STATIC_ROOT}),
    # ] + urlpatterns
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    

app_name = "root"
admin.site.site_header = "Family Enterprises"
admin.site.site_title = "Family Enterprises Accounting"
admin.site.index_title = "Welcome to Family Enterprises"

invoice/urls.py
from django.urls import path, include
import invoice.views as Views

urlpatterns = [
  path('id/<int:id>', Views.invoice, name="invoice_id"), 
  path('csid/<int:customer_id>', Views.invoice, name="cs_id"),
  path('orderid/<int:order_id>', Views.invoice, name="order_id"),  
]

app_name = 'invoice'

cashflow/models.py
from django.db import models
from nepali_date import NepaliDate
from django.db.models import Q
from django.contrib.auth.models import User


class PaymentMeta(models.Model):
    amount = models.FloatField()
    payment_mode = models.IntegerField(choices = ((1, "Cheque"), (2, "Cash"), (3,"Bank Transfer"), (4, "Internet Payment"), (5, "Transport"), (6, "Bank Deposit"), (7, "Goods Returned"), (8, "Discount")))
    date = models.DateField(null=True, blank=True)
    nepali_date = models.CharField(blank=True, max_length=20, default = "")
    term = models.ForeignKey("Term", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "%s" % self.amount

    def save(self, *args, **kwargs):
        if self.nepali_date != "":
            self.date = NepaliDate.to_english_date(NepaliDate(*self.nepali_date.split('-')))
        super(Payment, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class Payment(PaymentMeta):
    customer = models.ForeignKey('accounts.Customer', on_delete=models.CASCADE)


class DealerPaymnet(PaymentMeta):
    dealer = models.ForeignKey('accounts.Dealer', on_delete=models.CASCADE)


class Term(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField(max_length=300)

    def __str__(self):
        return self.title


class OpeningBalanceMeta(models.Model):
    account = models.ForeignKey("accounts.Customer", on_delete=models.CASCADE)
    amount = models.FloatField("Opening Balance") # blank=True, null=True)
    term = models.ForeignKey(Term, on_delete=models.CASCADE)

    def __str__(self):
        return "%s : %s" % (self.account.name, self.amount)

    def save(self, *args, **kwargs):
        if self.id:
            super(OpeningBalance, self).save(*args, **kwargs)
        else:
            if self.amount == 0:
                self.amount = self.account.remaining_pay()
            super(OpeningBalanceMeta, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('account', 'term')
        abstract = True

    @property
    def term_start(self):
        return self.term.start_date

    @property
    def term_end(self):
        return self.term.end_date

    def invoices(self):
        return self.account.salesinvoice_set.filter(
                date__range=[self.term.start_date, self.term.end_date]
            )

    def payments(self):
        return self.account.payment_set.filter(
                (Q(date__range=[self.term.start_date, self.term.end_date]) & Q(term__isnull = True)) | Q(term = self.term)
            )

    @property
    def closing_due(self):
        return sum(self.account.salesinvoice_set.filter(
                date__range=[self.term.start_date, self.term.end_date]
            ).values_list("to_pay", flat=True)) - \
            sum(self.account.payment_set.filter(
                date__range=[self.term.start_date, self.term.end_date]
            ).values_list('amount', flat=True)) + \
            self.amount

    @property
    def total_sales(self):
        return sum(self.account.salesinvoice_set.filter(
                date__range=[self.term.start_date, self.term.end_date]
            ).values_list("to_pay", flat=True))

    @property
    def total_pay(self):
        return sum(self.account.payment_set.filter(
            date__range=[self.term.start_date, self.term.end_date]
        ).values_list('amount', flat=True))


class OpeningBalance(OpeningBalanceMeta):
    def payments_until(self, end_date):
        return self.account.payment_set.filter(
            (Q(date__range=[self.term.start_date, end_date]) & Q(term__isnull = True)) | Q(term = self.term)
        ).values_list('amount', flat=True)
    
    def sales_until(self, end_date):
        return self.account.salesinvoice_set.filter(
                date__range=[self.term.start_date, end_date]
            ).values_list("to_pay", flat=True)


class OpeningBalanceDealer(OpeningBalanceMeta):
    account = models.ForeignKey("accounts.Dealer", on_delete=models.CASCADE)

cashflow/views.py
from django.shortcuts import render
import json
from accounts import models as Accounts
from products import models as Products
from invoice import models as Invoices
from market import models as Markets
from cashflow import models as CashFlows
from nepali_date.date import NepaliDate
from django.db.models import  Q
import pandas as pd
import nepali_datetime


def customer_details(request,id):
    openBal =CashFlows.OpeningBalance.objects.get(id=id)


    context = {
        "title": "%s-%s" %(openBal.account.name , openBal.term.title),
        "invoices": openBal.invoices,
        "payments": openBal.payments,
        "opening": openBal
    }
    return render (request, 'cashflow/customer_details.html', context=context)


def monthly_details(request, id, term): 
    customer = Accounts.Customer.objects.get(id =id)
    opening = CashFlows.OpeningBalance.objects.get(term__id = term, account = customer)
    nep_start = NepaliDate.to_nepali_date(opening.term.start_date)
    nep_end = NepaliDate.to_nepali_date(opening.term.end_date)
    if NepaliDate.today()< nep_end:
        nep_end = NepaliDate.today()
    all_calendar = pd.read_csv(nepali_datetime.calendar_file.name, index_col = 0)
    
    current_year = int(nep_start.year)
    current_month = int(nep_start.month)
    i = True
    titles = []
    openings = []
    sales = []
    payments = []
    id_tags = []
    opening_dates = []

    while (i):
        if current_month == 1:
            prev_month = 12
            prev_year = current_year - 1
        else:
            prev_month = current_month - 1
            prev_year = current_year

        
        year_calendar = all_calendar.loc[current_year]
        titles.append('%s:%s' % (current_year, year_calendar.index[current_month-1]))
        month_days = int(year_calendar[current_month-1])
        prev_month_days = int(year_calendar[prev_month-1])
        
        start_day = NepaliDate(prev_year, prev_month, prev_month_days).to_english_date()
        end_day = NepaliDate(current_year, current_month, month_days).to_english_date()
        opening_dates.append(start_day)
        monthly_opening = opening.amount + sum(opening.sales_until(start_day)) - sum(opening.payments_until(start_day))
        monthly_invoices = Invoices.salesInvoice.objects.filter(
            Q(date__gte = start_day) & Q(date__lte = end_day) & Q(issued_for=customer)
        )
        monthly_payments = CashFlows.Payment.objects.filter(
            Q(date__gte=start_day) & Q(date__lte=end_day) & Q(Q(term__isnull=True) | Q(term__id=term)) & Q(customer=customer)
        )
        
        i, current_month, current_year = update_loop(i, current_month, current_year, nep_end)
        openings.append(monthly_opening)
        sales.append(monthly_invoices)
        payments.append(monthly_payments)
        id_tags.append('%s%s'%(current_year, current_month))

    context = {
        'page_title': customer.name,
        'titles':titles, 'openings': openings, 'sales': sales, 'debits':payments, 'ids': id_tags,
        # 'titles_ids': zip(titles, id_tags),
        'accounts': zip(id_tags, openings, opening_dates, sales, payments, titles),
    }
    return render(request, 'cashflow/monthly_details.html', context=context)


def update_loop(i, current_month, current_year, nep_end):
    if (current_year == nep_end.year) & (current_month == nep_end.month):
        i = False
    if current_month == 12:
        current_month = 1
        current_year += 1
    else:
        current_month += 1
    return i, current_month, current_year


def term_monthly_details(request, term):
    opening_bals = CashFlows.OpeningBalance.objects.filter(term__id = term)
    opening_term = CashFlows.Term.objects.get(id=term)
    monthly_opening = sum(opening_bals.values_list('amount', flat=True))
    nep_start = NepaliDate.to_nepali_date(opening_term.start_date)
    nep_end = NepaliDate.to_nepali_date(opening_term.end_date)
    if NepaliDate.today()< nep_end:
        nep_end = NepaliDate.today()
    all_calendar = pd.read_csv(nepali_datetime.calendar_file.name, index_col = 0)
    
    current_year = int(nep_start.year)
    current_month = int(nep_start.month)
    i = True
    titles = []
    openings = []
    sales = []
    payments = []
    id_tags = []
    opening_dates = []
    cash_payments = []

    while (i):
        if current_month == 1:
            prev_month = 12
            prev_year = current_year - 1
        else:
            prev_month = current_month - 1
            prev_year = current_year

        
        year_calendar = all_calendar.loc[current_year]
        titles.append('%s:%s' % (current_year, year_calendar.index[current_month-1]))
        month_days = int(year_calendar[current_month-1])
        prev_month_days = int(year_calendar[prev_month-1])
        
        start_day = NepaliDate(current_year, current_month, 1).to_english_date()
        end_day = NepaliDate(current_year, current_month, month_days).to_english_date()
        opening_dates.append(start_day)
        monthly_invoices = Invoices.salesInvoice.objects.filter(
            Q(date__gte = start_day) & Q(date__lte = end_day) 
        ).prefetch_related('issued_for')
        monthly_payments = CashFlows.Payment.objects.filter(
            Q(date__gte=start_day) & Q(date__lte=end_day) & Q(Q(term__isnull=True) | Q(term__id=term))
        ).prefetch_related('customer')
        
        i, current_month, current_year = update_loop(i, current_month, current_year, nep_end)
        openings.append(monthly_opening)
        monthly_opening += sum(monthly_invoices.values_list('total', flat=True)) - sum(monthly_payments.values_list('amount', flat=True)) - sum(monthly_invoices.values_list('paid_amount', flat=True))
        sales.append(monthly_invoices)
        payments.append(monthly_payments)
        id_tags.append('%s%s'%(current_year, current_month))
        cash_payments.append({'amount':sum(monthly_invoices.values_list('paid_amount', flat=True)), 'date': end_day})

    context = {
        'page_title': "Monthly Summary",
        'titles':titles, 'openings': openings, 'sales': sales, 'debits':payments, 'ids': id_tags,
        'titles_ids': zip(titles, id_tags),
        'accounts': zip(id_tags, openings, opening_dates, sales, payments, titles, cash_payments), 
    }
    return render(request, 'cashflow/monthly_details_term.html', context=context)

invoice/views.py
from django.shortcuts import render
import json
from accounts import models as Accounts
from products import models as Products
from invoice import models as Invoices
from market import models as Markets
from users import models as Users
from invoice.serializer import ItemSerializer


def invoice(request, order_id=None, id=None, customer_id=None):
    items_ = Products.ItemColorAvailability.objects.all().prefetch_related('item', 'color')
    items = []
    items_list = []
    cart = Markets.ShoppingCart()
    unsaved = True

    for x in items_:
        items_list.append({x.id: x.__str__()})
        
    if id is not None:
        items = Invoices.salesItem.objects.filter(salesInvoice__id=id)
        invoice = Invoices.salesInvoice.objects.get(id=id)
        customer = invoice.issued_for
        owner = invoice.issued_by.usertype.belongs_to_dealer
        cart = invoice.order_no

    elif order_id is not None:
        cart = Markets.ShoppingCart.objects.get(id=order_id)
        customer = cart.customer
        try:
            invoice = Invoices.salesInvoice.objects.filter(order_no=order_id)[0]
            items = Invoices.salesItem.objects.filter(salesInvoice=invoice)
        except:
            invoice = Invoices.salesInvoice(issued_for=customer, issued_by=request.user)
            items = Markets.ShoppingItems.objects.filter(cart__id=order_id)
        owner = Users.UserType.objects.get(user=request.user).belongs_to_dealer


    else:
        customer = Accounts.Customer.objects.get(id=customer_id)
        owner = Users.UserType.objects.get(user=request.user).belongs_to_dealer
        invoice = Invoices.salesInvoice(issued_for=customer, issued_by=request.user)
    
    if not request.user.is_superuser:
        unsaved = False # Do not allow other customers to edit the invoice.

    context = {
        'customer': customer, 
        'items_list': json.dumps(items_list),
        'items': items,
        'invoice': invoice,
        'owner': owner,
        'cart': cart,
        "unsaved": unsaved,
        "due" : round(customer.arthik_remaining_pay, 2),
        'order': cart
    }

    if request.method == "POST":
        data = request.POST
        items_post = json.loads(data['items'])
        invoiceDetails = json.loads(data['invoice'])
        try:
            invoice.total = invoiceDetails['total']
            invoice.tax = invoiceDetails['tax']
            invoice.paid_amount = invoiceDetails['paid']
            invoice.date = invoiceDetails['date']
            invoice.discount = invoiceDetails['discount']
            invoice.to_pay = invoiceDetails['to_pay']
            invoice.notes = invoiceDetails['notes']
            invoice.is_posted = True
            invoice.bill_no = invoiceDetails['vat']
            invoice.order_no = cart
            invoice.save()
            invoice = Invoices.salesInvoice.objects.get(id=invoice.id)
            cart.paid_status = 5
            cart.save()
        except:
            context["errors"]= "Error in Details of Invoice"
            return(request, 'cashflow/invoice.html', context)

        items = Invoices.salesItem.objects.filter(salesInvoice=invoice)
        already_saved_ids = items.values_list('id', flat=True)
        saved_items_id = []
        for posted_item in items_post:
            posted_item['salesInvoice'] = invoice.id
            if posted_item['id'] == "":
                item_save = ItemSerializer(data=posted_item)
            else:
                item_saved = Invoices.salesItem.objects.get(id=posted_item["id"])
                item_save = ItemSerializer(instance=item_saved, data=posted_item)
            if item_save.is_valid():
                item_saved = item_save.save()
            else:
                context.update({
                        "errors":"Error in Item " + posted_item['description']
                    })
                return(request, 'cashflow/invoice.html', context)

            saved_items_id.append(item_saved.id)

        to_delete = list(
            set(already_saved_ids) - set(saved_items_id)
        )
        Invoices.salesItem.objects.filter(id__in = to_delete).delete()
        items = Invoices.salesItem.objects.filter(salesInvoice=invoice)
        context.update({
        "id" : id,
        "invoice": invoice,
        "user": request.user,
        "owner": owner,
        "items": items,
        "customer" : customer,
        "unsaved": False,
        "due" : customer.remaining_pay(),
        'order':cart
        })
        return render(request, 'cashflow/invoice.html', context)

    return render(request, template_name="cashflow/invoice.html", context=context)

templates/cashflow/invoice.html
<html> {% load static %}
	<head>
		<meta charset="utf-8">
		<title>Invoice</title>
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="license" href="https://www.opensource.org/licenses/mit-license/">
		<link href="{% static 'css/nepali.datepicker.v3.2.min.css' %}" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<script type="text/javascript">
            var items_list = JSON.parse('{{items_list | safe}}');

			function convert(){
				console.log("registered Change");
				var input = document.getElementById('nepali-datepicker');
				nep_date_obj = {
					"year": parseInt(input.value.split('-')[0]),
					"month": parseInt(input.value.split('-')[1]),
					"day": parseInt(input.value.split('-')[2])
				}
				var eng_place = document.getElementById('engdate');
				eng_place.value = NepaliFunctions.ConvertDateFormat( NepaliFunctions.BS2AD(nep_date_obj));
			}
			window.onload = function() {
				// var inputs = document.getElementsByClassName('nepali-datepicker');
				var input = document.getElementById('nepali-datepicker');
				input.nepaliDatePicker();
				today = NepaliFunctions.GetCurrentBsDate();
				var eng_place = document.getElementById('engdate');
				var date_system = "{{ invoice.date | date:'Y-m-d' | default_if_none:''}}";
				{% if invoice.date %}
				if (date_system !== ""){
					today = NepaliFunctions.AD2BS({
						"year": {{invoice.date | date:'Y'}},
						"month": {{invoice.date | date:'m'}},
						"day":{{invoice.date | date:'d'}}
					});
				}
				{% endif %}
				if (input.value == "" & eng_place.value == ""){
					input.value = NepaliFunctions.ConvertDateFormat(today);
				}
				nep_date_obj = {
					"year": parseInt(input.value.split('-')[0]),
					"month": parseInt(input.value.split('-')[1]),
					"day": parseInt(input.value.split('-')[2])
				}
				var eng_place = document.getElementById('engdate');
				eng_place.value = NepaliFunctions.ConvertDateFormat( NepaliFunctions.BS2AD(nep_date_obj));

				// for (var i = 0; i < inputs.length; i++) {
				// 	inputs[i].nepaliDatePicker();
				// }
				{% if unsaved == False %} if (window.print()){
					location.replace("{% url 'invoice:invoice_id' id=invoice.id %}");
				};
				{% endif %}
			}
			function beforeSubmit(){
				convert();
				invoice = document.getElementById("invoice");

				invoice_details = JSON.parse(invoice.value);
				invoice_details['vat'] = document.getElementById("vat_no").value
				invoice_details['date'] = document.getElementById("engdate").value
				invoice_details['notes'] = document.getElementById("notes").innerHTML
				invoice_details['order_id'] = document.getElementById("order_id").value
				invoice.value = JSON.stringify(invoice_details)


				document.getElementById("form").submit();
				return true;
			}
		</script>
		<header>
			<h1><a href="{% url 'admin:accounts_customer_change' object_id=customer.id %}">Invoice</a></h1>
			<address contenteditable>
				<p>{{owner.name | default_if_none:''}}</p>
				<p>{{owner.address | default_if_none:''}}, Contact No.:{{owner.phone | default_if_none:''}}, Email: {{owner.email | default_if_none:''}}</p>
				<p>PAN:{{owner.pan | default_if_none:''}}</p>
				{% if owner.contact_person %}
				<p>Billed By: {{user.first_name }} {{user.last_name}}</p>
				{% endif %}
			</address>
			<form action="{% url 'invoice:order_id' order_id=order.id %}" id="form" method="post">
				<input type="hidden" name="items" id="items" />
				<input type="hidden" name="invoice" id="invoice" />
				{% csrf_token %}
				{% if unsaved %} <button style="color:red; background-color: black; padding: 5px;" onclick="beforeSubmit();" type="button">Save & Print</button> <span>Max Items in Bill: 20</span> {% endif %}
			</form>
			<!-- <span><img alt="" src="http://www.jonathantneal.com/examples/invoice/logo.png"><input type="file" accept="image/*"></span> -->
		</header>
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<p>{{customer.name | default_if_none:''}}<br>c/o{% if customer.contact_person %} {{customer.contact_person.name}} {% endif %}</p>
				<p>{{customer.address | default_if_none:''}}</p>
				<p>{{customer.phone | default_if_none:''}}</p>
				<p>PAN:{{customer.pan | default_if_none:''}}</p>
			</address>
			<table class="meta">
				<tr>
					<th><span contenteditable>Invoice #</span></th>
					<td colspan="2"><span contenteditable>{{invoice.id}}</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Date</span></th>

					<td><input id="nepali-datepicker" onchange="convert();" /></td>
					<td><input id="engdate"/>{% if unsaved %}
						<button onclick="convert()">EngDate</button>
						{% endif%}</td>
				</tr>
				<input id="order_id" type="hidden" value={{order.id}}>
				<tr>
					<th><span contenteditable>Vat Bill No.</span></th>
					<td colspan="2"><input id="vat_no" value="{{invoice.bill_no | default_if_none:''}}" /></td>
				</tr>
				<tr>
					<th><span contenteditable>Due Amount</span></th>
					<td colspan="2"><span id="prefix" contenteditable>रु</span><span>{{due}}</span></td>
				</tr>
			</table>
			<table class="inventory">
				<thead>
					<tr>
						<th width="20"><span contenteditable>N</span></th>
						<th width="150" style="visibility:hidden; display:none;"><span contenteditable>Item Description</span></th>
                        <th width="350"><span contenteditable>Description</span></th>
						<th width="60"><span contenteditable>Rate</span></th>
						<th width="60"><span contenteditable>QTY</span></th>
						<th width="90"><span contenteditable>Price</span></th>
						<th width="15"><span contenteditable>Tax</span></th>
						<th width="15"><span contenteditable>Inc</span></th>
						<th width="0" style="visibility: hidden; display:none"></th>
					</tr>
				</thead>
				<tbody>
				{% if invoice.id %}
					{% for item in items %}
					<tr>
						<td><span contenteditable>1</span></td>
						<td style="visibility:hidden; display:none;"><span class="selector" id="sel_{{item.id}}" value="{{item.item_id}}">{{item.item.id}}</span></td>
                        <td class="left"><span contenteditable>{{item.description}}</span></td>
						<td class="right"><span data-prefix>रु</span><span contenteditable>{{item.rate |floatformat }}</span></td>
						<td class="right"><span contenteditable>{{item.qty|floatformat }}</span></td>
						<td class="right"><span data-prefix>रु</span><span>{{item.price|floatformat }}</span></td>
						<td class="center"><span contenteditable>{% if item.taxable %}x{% endif %}</span></td>
						<td class="center"><span contenteditable>{% if item.tax_include %}x{% endif %}</span></td>
						<td width="0" style="visibility:hidden; display:none"><span>{{item.id}}</span></td>
					</tr>
					{% endfor %}
				{% else %}
				{% for item in items %}
					<tr>
						<td><span contenteditable>1</span></td>
						<td style="visibility:hidden; display:none;"><span class="selector" id="sel_{{item.id}}" value="{{item.item_id}}">{{item.item.id}}</span></td>
                        <td class="left"><span contenteditable>{{item.item}}</span></td>
						<td class="right"><span data-prefix>रु</span><span contenteditable>{{item.rate |floatformat }}</span></td>
						<td class="right"><span contenteditable>{{item.qty|floatformat }}</span></td>
						<td class="right"><span data-prefix>रु</span><span>{{item.price|floatformat }}</span></td>
						<td class="center"><span contenteditable>{% if item.taxable %}x{% endif %}</span></td>
						<td class="center"><span contenteditable>{% if item.tax_include %}x{% endif %}</span></td>
						<td width="0" style="visibility:hidden; display:none"><span></span></td>
					</tr>
					{% endfor %}
				
				{% endif %}
				</tbody>
			</table>
			<a class="add">+</a>
			<table class="balance">
				<tr>
					<th><span contenteditable>Total</span></th>
					<td><span data-prefix>रु</span><span>600.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Paid</span></th>
					<td><span data-prefix>रु</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>TAX 13%</span></th>
					<td><span data-prefix>रु</span><span>70.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Grand Total</span></th>
					<td><span data-prefix>रु</span><span>600.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Discount</span></th>
					<td><span data-prefix>रु</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Balance Due</span></th>
					<td><span data-prefix>रु</span><span>600.00</span></td>
				</tr>
			</table>
		</article>
		<aside>
			<h1><span contenteditable>Additional Notes</span></h1>
			<div contenteditable id="notes">
				{% if invoice.notes %} {{invoice.notes | safe}} {% else %}1.{% endif %}
			</div>
		</aside>




        <script src="{% static 'js/run.js' %}"></script>
		<script src="{% static 'js/nepali.datepicker.v3.2.min.js' %}" type="text/javascript"></script>
	</body>
</html>